name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    environment: deploy
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@master
        - name: Publish to Registry
          uses: elgohr/Publish-Docker-Github-Action@master
          with:
            name: buremba/metriql
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            tags: "latest"
        - name: Update Demo on Heroku
          uses: CamiloGarciaLaRotta/watermelon-http-client@v1.5
          with:
            url: https://kolkrabbi.heroku.com/apps/2748b834-4cc7-409c-819c-f7aa907d8f46/github/push
            method: POST
            headers: '{"Authorization": "Bearer ${{ secrets.DEMO_HEROKU_API_TOKEN }}"}'
            verbose: true
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout project
#        uses: actions/checkout@v2
#      - name: Cache local Maven repository
#        uses: actions/cache@v2
#        with:
#          path: ~/.m2/repository
#          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
#          restore-keys: ${{ runner.os }}-maven-
#      - name: Setup Java JDK
#        uses: actions/setup-java@v2
#        with:
#          java-version: 8
#          distribution: 'adopt'
#          server-id: github
#      - name: Configure Git user
#        run: |
#          git config user.email "actions@github.com"
#          git config user.name "GitHub Actions"
#      - name: Publish JAR
#        run: ./mvnw -B -DskipTests -Darguments=-DskipTests release:prepare release:perform
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
